### ISSUE TITLE
Creating index(es) using Mongo.jl

### ISSUE THREAD

**Issue by bmharsha** [pzion/Mongo.jl#13]
Is there a way to create indexes on a particular column using Mongo.jl?

I was looking for an API that replicates this function `db.collection.createIndex()`

**Comment by ghost** [comment]
I don't think there is but it should be very easy to add, I would recommend looking at the source code for this module and seeing if it's indeed straightforward.

**Comment by bmharsha** [comment]
Thanks @ivirshup and @pzion , PR https://github.com/pzion/Mongo.jl/pull/14 fixes this issue
