### ISSUE TITLE
Problem installing mongo.jl on Mac OS

### ISSUE THREAD

**Issue by rogerwhitney** [pzion/Mongo.jl#19]
I am new to Julia and am trying to use the Mongo package. I am using Julia 0.4.6 on Mac OS 10.11.6. When I try to add (or build) the package using Pkg.add("Mongo") or Pkg.build("Mongo")I get the error:

"Error: Cannot install mongo-c because conflicting formulae are installed.
  libbson: because mongo-c installs the libbson headers
Please `brew unlink libbson` before continuing.

Unlinking removes a formula's symlinks from /Users/whitney/.julia/v0.4/Homebrew/deps/usr. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software."

I then tried to unlink libbson using: Homebrew.brew(`unlink libbson`) and then tried building Mongo again, but had the same error.

**Comment by n-raghu** [comment]
[MongoPackageError.txt](https://github.com/pzion/Mongo.jl/files/460918/MongoPackageError.txt)

I am also facing the same issue, unable to add Mongo package in Julia. Getting the same error.
I am using El Capitan and the version of Julia is 0.4.6

**Comment by ghost** [comment]
Thanks guys, looks like something changed in Homebrew, I'm trying out a fix right now.

**Comment by ghost** [comment]
This should now be fixed, please re-open if you are still experiencing this issue after `Pkg.update()` then `Pkg.add("Mongo")`

**Comment by n-raghu** [comment]
thanks @pzion , its now working.

**Comment by rogerwhitney** [comment]
Working for me too. Thanks.

---

Roger Whitney              Department of Computer Science
whitney@sdsu.edu        San Diego State University
http://www.eli.sdsu.edu/   San Diego, CA 92182-7720
