### ISSUE TITLE
Cannot build Mongo after upgrading to Julia-0.6

### ISSUE THREAD

**Issue by einaro23** [pzion/Mongo.jl#26]
When trying to build Mongo.jl after I upgraded from Julia0.5 to Julia0.6 I get the error message:

=====================================================================================================================================================================
INFO: Building Mongo
==========================================================================[ ERROR: Mongo ]===========================================================================

LoadError: UndefVarError: @osx_only not defined
while loading /Users/xxx/.julia/v0.6/Mongo/deps/build.jl, in expression starting on line 21

Is this an issue with Mongo.jl?

**Comment by ghost** [comment]
This should now be fixed!  The master branch is v0.3.0 and it works on both Julia v0.5 and Julia v0.6
