### ISSUE TITLE
Can't open file Mongo.jl, deps.jl, libBSON, etc. 

### ISSUE THREAD

**Issue by hpoit** [pzion/Mongo.jl#4]
Hi, 

I have Julia 0.3, Mongodb-osx-x86_64-3.0.4, and Mongo-c-driver-1.1.9 installed, but can't get Julia to access the Mongo Client through this 'untestable' package https://github.com/pzion/Mongo.jl, according to  http://pkg.julialang.org/. 

I have tried Lytol/Mongo.jl and the command require("Mongo.jl") can't open file Mongo.jl, or the auto-generated deps.jl. 

I will attempt to debug it and publish my findings on Github. 

Connection to Julia users on Google Groups https://groups.google.com/d/msg/julia-users/h4NxY6vLdnM/YT7B_UOWZZsJ

**Comment by ghost** [comment]
I think this is quite old, I will close it but please re-open if this is still an issue for you with a more recent version of Julia.
